-- MySQL syntax

CREATE TABLE IF NOT EXISTS EXCHANGE_TRANSACTION (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TOOL_NAME VARCHAR(10) NOT NULL,
    VOLUME DECIMAL(20,10) NOT NULL,
    PRICE1 DECIMAL(20,10) NOT NULL,
    PRICE2 DECIMAL(20,10) NOT NULL,
    TRANSACTION_TIMESTAMP TIMESTAMP NOT NULL,
    INDEX EXCHANGE_TRANSACTION_TOOL_NAME (TOOL_NAME)
);
