-- MySQL syntax

CREATE TABLE IF NOT EXISTS EXCHANGE_TRANSACTION (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TOOL_NAME VARCHAR(10) NOT NULL,
    VOLUME BIGINT NOT NULL,
    TRANSACTION_TIMESTAMP TIMESTAMP NOT NULL,
    INDEX EXCHANGE_TRANSACTION_TOOL_NAME_INDEX (TOOL_NAME)
);
